##
## Build with Travis.CI
##
#
language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11
  
# needed to get openjdk8 to work
dist: trusty
    
env:
# do a few less tests to not hit timeouts (see TestTools.java in tests package)
  -FASTTESTS=true
    
# Cache Maven dependencies to speed up builds.
cache:
  directories:
  - $HOME/.m2
  
# trigger the build of aitoa book after success
jobs:
  include:
    - stage: deploy
      script: sh trigger-travis.sh thomasWeise aitoa $TRAVIS_ACCESS_TOKEN